# Generated by Django 5.1.5 on 2025-02-05 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese'), ('CK', 'Cakes')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('A&N', 'Andaman & Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('ARP', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BH', 'Bihar'), ('CG', 'Chandigarh'), ('CTG', 'Chattisgarh'), ('D&NH', 'Dadra & Nagar Haveli'), ('D&D', 'Daman and Diu'), ('DL', 'Delhi'), ('GO', 'Goa'), ('GJ', 'Gujrat'), ('HY', 'Haryana'), ('HP', 'Himachal Pradesh'), ('J&K', 'Jammu & Kashmir'), ('JK', 'Jharkhand'), ('KT', 'Karnataka'), ('KL', 'Kerala'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MAH', 'Maharashtra'), ('MAN', 'Manipur'), ('MEG', 'Meghalaya'), ('MIZ', 'Mizuran'), ('NAG', 'Nagaland'), ('OD', 'Odisa'), ('PDC', 'Puducherry'), ('PUN', 'Punjab'), ('RAJ', 'Rajasthan'), ('SK', 'Sikkim'), ('T&N', 'Tamil Nadu'), ('TEL', 'Telangana'), ('TRI', 'Tripura'), ('UTT', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
