# Generated by Django 5.1.5 on 2025-02-07 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('A&N', 'Andaman & Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('ARP', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BH', 'Bihar'), ('CG', 'Chandigarh'), ('CTG', 'Chattisgarh'), ('D&NH', 'Dadra & Nagar Haveli'), ('D&D', 'Daman and Diu'), ('DL', 'Delhi'), ('GO', 'Goa'), ('GJ', 'Gujarat'), ('HY', 'Haryana'), ('HP', 'Himachal Pradesh'), ('J&K', 'Jammu & Kashmir'), ('JK', 'Jharkhand'), ('KT', 'Karnataka'), ('KL', 'Kerala'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MAH', 'Maharashtra'), ('MAN', 'Manipur'), ('MEG', 'Meghalaya'), ('MIZ', 'Mizuran'), ('NAG', 'Nagaland'), ('OD', 'Odisa'), ('PDC', 'Puducherry'), ('PUN', 'Punjab'), ('RAJ', 'Rajasthan'), ('SK', 'Sikkim'), ('T&N', 'Tamil Nadu'), ('TEL', 'Telangana'), ('TRI', 'Tripura'), ('UTT', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal')], max_length=100),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
